# Generated by Django 4.1 on 2022-09-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='execution',
            name='state',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='execution',
            name='result',
            field=models.FileField(upload_to=None),
        ),
    ]
